### ISSUE TITLE
helm chart

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/externalip-webhook#7]
Any plan for a helm chart?

**Comment by SaranBalaji90** [comment]
@kfox1111, I will take a look this week.

**Comment by rawmind0** [comment]
@SaranBalaji90 , if helps you, we've already made one, https://github.com/rancher/externalip-webhook/tree/master/chart

**Comment by kfox1111** [comment]
awesome. thanks for sharing. :)

**Comment by kfox1111** [comment]
random broader question. should kubernetes-sigs get its own helm repo?

**Comment by SaranBalaji90** [comment]
Awesome.. Thank you so much @rawmind0 :)
