### ISSUE TITLE
make cert usage optional or configurable

### ISSUE THREAD

**Issue by rgarcia89** [kubernetes-sigs/externalip-webhook#9]
It would be nice if cert usage could be set to optional or at least the name of the certs in the directory could be set manually.

**Comment by SaranBalaji90** [comment]
Thank you @rgarcia89 for filing the issue. Controller-runtime excepts certs to be available for serving webhook endpoint and certs directory is configurable (https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options).

Can you clarify the following questions regarding your feature request - 

1) Intention for making cert usage to be optional, is it to serve webhook on http instead of https?
2) By name of the certs do you mean the actual server certs (tls.crt and tls.key)?

**Comment by rgarcia89** [comment]
@SaranBalaji90 I am asking because I have configured a cert and ca using cssljson, I have also placed it correctly. 
Pod is coming up, everything looks fine, caBundle has been updated etc.

However, I get the following issue on every service create/update
`2020/12/16 10:53:25 http: TLS handshake error from 10.101.1.128:44160: remote error: tls: bad certificate`

**Comment by SaranBalaji90** [comment]
@rgarcia89 I tried with with cfssl and it seems to work as expected.

Step-1:
`cfssl gencert  -ca=ca.pem  -ca-key=ca-key.pem  -config=ca-config.json  -hostname=externalip-validation-webhook-service.externalip-validation-system.svc  -profile=server   server-csr.json | cfssljson -bare server`

Step-2:
`kubectl create secret tls webhook-server-cert --cert=server.pem --key=server-key.pem -n externalip-validation-system`

Step-3:
Updated ValidatingWebhookConfiguration `caBundle` with output of `cat ca.pem | base64` and everything seems to work.

Step-4:
Applied the service file and saw the following error
`Error from server (spec.externalIPs: Invalid value: "10.0.0.3": externalIP specified is not allowed to use): error when creating "clb-svc-2.yaml": admission webhook "validate-externalip.webhook.svc" denied the request: spec.externalIPs: Invalid value: "10.0.0.3": externalIP specified is not allowed to use`

**Comment by rgarcia89** [comment]
@SaranBalaji90 good to know. In that case something must be wrong with my ca-config.json. Which usage types do you have set and which address?

Thanks in advance

**Comment by rgarcia89** [comment]
Got it working - I was missing some parameters in the usage section.
Works fine now - Thanks :)
